== [orange]#HELM - Gestion des Secrets#

Sécuriser l'accès au backend via une authentification basique

=== Plan

[%step]
* Prerequis technique
** Génération d'une clef PGP
** Encodage des fichiers secrets.yaml via SOPS (basé sur la clef PGP)
** Modification des fichiers secrets.yaml via helm secrets
* Mise en place de l'authentification
** Création du secret htpasswd
** Création de la configuration NGinx
** Déploiement de l'application

=== Génération d'une clef PGP

[source, bash]
----
gpg --full-generate-key
gpg (GnuPG) 2.2.8; Copyright (C) 2018 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Sélectionnez le type de clef désiré :
   (1) RSA et RSA (par défaut)
   (2) DSA et Elgamal
   (3) DSA (signature seule)
   (4) RSA (signature seule)
Quel est votre choix ?
les clefs RSA peuvent faire une taille comprise entre 1024 et 4096 bits.
Quelle taille de clef désirez-vous ? (3072)
La taille demandée est 3072 bits
...
Nom réel : opus-softeam
Adresse électronique : mehdi.elkouhen@softeam.fr
Commentaire :
Vous avez sélectionné cette identité :
    « opus-softeam <mehdi.elkouhen@softeam.fr> »
----

=== Création d'un fichier Metadata SOPS

[source, bash]
----
# gpg --list-secret-keys
/home/elkouhen/.gnupg/pubring.kbx
---------------------------------
sec   rsa3072 2018-11-26 [SC] [expire : 2019-11-26]
      59D14BD4108D748C3E9FF048EB31F93C01C4EDDC
uid          [  ultime ] opus-softeam <mehdi.elkouhen@softeam.fr>
ssb   rsa3072 2018-11-26 [E] [expire : 2019-11-26]

# cat .sops.yaml
creation_rules:
  - pgp: '59D14BD4108D748C3E9FF048EB31F93C01C4EDDC'
----

=== Création du fichier de secrets

[source, yaml]
----
# sops -i -e secrets.yaml
# cat secrets.yaml
auth:
    htpassword: ENC[AES256_GCM,data:DwM61IYHNpJrX0Qf5DaUbWC2CzcKROFgVFt/Ry8w9t6dVm97M9w1YUMVNQjR8ZKbaGMVfqbL5YBbbAps,iv:rQgGF0kHFq5B6y1GZy6ORx/KMBfWOBf43hVfNRqaLCk=,tag:5H++7uKF1eIEI+uCPvvl/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    lastmodified: '2018-12-12T13:23:55Z'
    mac: ENC[AES256_GCM,data:FbSvNsjuRbPITXGTP1xQw4Clsv7l9x8rfrlebzwPders+2JInX8DBNq8UuvLy2j/CA+QIVF7hBCm3KLdqkwdMhdY5ic4ogIvYRJUJm9Bnvv9bBKvwsXfA/EO6Zler3fXnpQ3ey+ZNurvYqgeMyMB3ft80KTJCxdInYZ7nymFDg8=,iv:oM6d+i+oC8i3tSeuu3apzIsJCXyK86tPJO2NVuxaApA=,tag:c2p7Wy0qVJn2DwrL/fhAjQ==,type:str]
    pgp:
    -   created_at: '2018-12-12T13:23:55Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            -----END PGP MESSAGE-----
        fp: 0E20EFE4D1A4AC5DBA9DC014FB5D621EBDC94F27
    unencrypted_suffix: _unencrypted
    version: 3.0.3
----

=== Décodage du fichier de secrets

[source, yaml]
----
# sops -i -d secrets.yaml
----

=== Edition du fichier de secrets

[source, yaml]
----
# helm secrets edit secrets.yaml
----

== [orange]#HELM - Gestion du secret htpasswd#

* Chiffrement du login/mot de passe

=== Création du secret htpasswd

[source, yaml]
----
# cat basicauth.yml

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-basicauthsecret
data:
  auth: {{ .Values.auth.htpassword }}
----

=== Configuration de l'authentification basic (NGinx)

[source, yaml]
----
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/issuer: letsencrypt-issuer
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret:  books-api-basicauthsecret
    nginx.ingress.kubernetes.io/auth-type: basic
----

=== Déploiement du Package Helm

[source, bash]
----
# helm secrets install --name books-api --values secrets.yaml  .
----
